// aprendiendo-vue/src/components/Articles.vue
<template>
  <section id="articles-component">
    <div v-if="!articles">Cargando...</div>
    <div id="articles-list" v-if="articles && articles.length >= 1">
      <article class="article-item" v-for="article in articles" :key="article._id">
        <div class="image-wrap">
          <img :src="url+'get-image/'+article.image" :alt="article.title" v-if="article.image" />
          <img src="../assets/images/no-image.jpg" :alt="article.title" v-if="!article.image" />
        </div>
        <h2>{{article.title}}</h2>
        <span class="date">{{article.date}}</span>
        <a href="#">Leer más</a>
        <div class="clearfix"></div>
      </article>
    </div>
    <div v-else-if="articles && articles.length < 1">
      No hay artículos para mostrar
    </div>
    <div v-else>
      Cargando...
    </div>
  </section>
</template>

<script>
import Global from "../Global";
export default {
  name: "Articles",
  props: ["articles"],
  data() {
    return {
      url: Global.url,
    };
  },
};
</script>

// AprendiendoAngular/src/app/components/articles/articles.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Article } from '../../models/article';
import { Global } from '../../services/global';

@Component({
  selector: 'app-articles',
  templateUrl: './articles.component.html',
  styleUrls: ['./articles.component.css']
})
export class ArticlesComponent implements OnInit {

  public url: string;

  @Input() articles: Article[];

  constructor() { 
    this.url = Global.url;
  }

  ngOnInit(): void {
    
  }

}


<!--Efecto de cargando...-->
<div class="loading" *ngIf="!articles">
    Cargando...
</div>

<div class="loading" *ngIf="articles && articles.length == 0">
    No hay artículos para mostrar, inténtalo más tarde.
</div>

<div id="articles" *ngIf="articles">
    <article class="article-item" *ngFor="let article of articles">
        <div class="image-wrap">
            <img src="{{url + 'get-image/' + article.image}}" alt="{{article.title}}" *ngIf="article.image">
            <img src="assets/images/default.png" alt="{{article.title}}" *ngIf="!article.image">
        </div>
        <h2>{{article.title}}</h2>
        <span class="date">
            {{article.date | amLocale: 'es' | amTimeAgo}}
        </span>
        <a [routerLink]="['/blog/articulo', article._id]">Leer más</a>
        <div class="clearfix"></div>
    </article>

</div>
